### ISSUE TITLE
Backend Integration: Secure API Endpoints

### ISSUE THREAD

**Issue by jessmphelan** [jessmphelan/PhishingEvaluationGame#7]
**Description:** Add basic security measures to your API endpoints

**Steps:**

- Research and choose an appropriate method for securing your API 
- Implement the chosen security measure in your server.
- Test the security implementation to ensure it works as expected without hindering legitimate use.

**Expected Outcome:** The API should be more resistant to common abuse patterns like excessive requests.

**Comment by lauradbryant** [comment]
Are we sure we want to use a rate limiter as it might interfere if the project is scaled and many people are trying to play the game at the same time?

How are we thinking of implementing API keys? Do we want the user to have to make an account? Carlos had mentioned maybe generating an API key based off the demographic information without the user having to create a password. How would that work and have we implemented the demographic form in the game yet to be ready to set that up?

**Comment by lauradbryant** [comment]
Great! I know nothing about frontend but I'll start looking at it and see what I can figure out.
